# Generated by Django 2.2.8 on 2019-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('owner', models.CharField(default='Dude', max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
